version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.0.1
      rails_version:
        type: string
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: 'active-fedora'

      - samvera/rubocop

      - run: bundle exec rake

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.3
          rails_version: 5.2.3
      - bundle_lint_test:
          name: ruby2-5_rails5-2
          ruby_version: 2.5.5
          rails_version: 5.2.3
      - bundle_lint_test:
          name: ruby2-4_rails5-2
          ruby_version: 2.4.6
          rails_version: 5.2.3
      - bundle_lint_test:
          name: ruby2-6_rails5-1
          ruby_version: 2.6.3
          rails_version: 5.1.7
      - bundle_lint_test:
          name: ruby2-5_rails5.1
          ruby_version: 2.5.5
          rails_version: 5.1.7
      - bundle_lint_test:
          name: ruby2-4_rails5-1
          ruby_version: 2.4.6
          rails_version: 5.1.7
